Flask/FlaskDB/AI/views/auth_views.py
from flask import Blueprint , render_template , request , url_for , flash , session , g
from AI.forms import UserCreateForm , UserLoginForm
from .. import db
from AI.models import User , Question
from werkzeug.utils import redirect
from werkzeug.security import generate_password_hash , check_password_hash
from datetime import datetime
import functools # login_required 데코레이터

# @login_required 데코레이터
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.signin', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

bp =Blueprint('auth' , __name__ , url_prefix='/auth')

# 회원가입
@bp.route('/signup' , methods = ('GET' , 'POST'))
def signup():
    form = UserCreateForm()
    print("-"*10)
    if request.method == 'POST' and form.validate_on_submit():
        print('-'*10)
        user = User.query.filter_by(username = form.username.data).first()
        if not user:
            user = User(username = form.username.data , password = generate_password_hash(form.password1.data) ,
                        name = form.name.data , birthday = form.birthday.data , gender = form.gender.data , address1 = form.address1.data ,
                        address2 = form.address2.data , email = form.email.data , phone = form.phone.data , reg_date = datetime.now())
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("main.index"))
        else:
            flash("이미 존재하는 유저입니다.")
    return render_template('auth/signup.html' , form=form)

# 로그인
@bp.route('/signin/', methods=('GET', 'POST'))
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/sign.html', form=form)

@bp.route('/profile/<int:userid>')
def profile(userid):
    # 사용자 정보
    user = User.query.filter_by(id = userid).first()

    # 컨텐츠 리스트
    posts = Question.query.filter(Question.user_id == User.id).order_by(Question.id.desc()).all();
    # bp.logger.debug(len(posts))

    return render_template('auth/profile_modify.html' , user=user , Question=Question , userid=userid)

# 로그아웃 ( 가장 먼저 유저정보를 받아 모든 views 파일중에 가장먼저 실행되는 라우팅 함수 )
@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

# 로그아웃 실제 처리
@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

Flask/FlaskDB/AI/views/game_views.py
from flask import render_template,Response,Blueprint , g
import cv2
import cvzone
from cvzone.FaceMeshModule import FaceMeshDetector
import mediapipe as mp
import numpy as np
from PIL import ImageFont, ImageDraw, Image
import pandas as pd
from ..AI_model import eyeTest as et
import datetime
import time
import random
import os

bp = Blueprint('game' , __name__ , url_prefix='/game')

@bp.route('/game')
def game():
    return render_template('test/game.html')

totalTime = 30  # 총 게임 시간은 20초로 지정
userID = '000000001'
eye_dist = 33

now = datetime.datetime.now()
nowDatetime = now.strftime('%Y-%m-%d %H:%M:%S')

font = ImageFont.truetype('../AI/static/fonts/H2GSRB.TTF', 35)
small_font = ImageFont.truetype('../AI/static/fonts/H2GSRB.TTF', 10)
logo = cv2.resize(cv2.imread('C:/Users/user/Desktop/pythonProject/pythonProject/Git/Flask/FlaskDB/AI/static/assets/img/button/eye.png', cv2.IMREAD_UNCHANGED), (80, 80))

cap = cv2.VideoCapture(0)
cap.set(3, 1280)
cap.set(4, 720)

detector = FaceMeshDetector(maxFaces=1)
mp_hands = mp.solutions.hands

detector = FaceMeshDetector(maxFaces=1)
idList = [0, 17, 78, 292]

# import images
folderBirds = 'C:/Users/user/Desktop/pythonProject/pythonProject/Git/Flask/FlaskDB/AI/static/image/game'
ListBirds = os.listdir(folderBirds)
catch = []
for object in ListBirds:
    catch.append(cv2.resize(cv2.imread(f'{folderBirds}/{object}', cv2.IMREAD_UNCHANGED), (80, 80)))
background = cv2.resize(cv2.imread('C:/Users/user/Desktop/pythonProject/pythonProject/Git/Flask/FlaskDB/AI/static/assets/img/button/background.jpg'), (1000, 630))

currentObject = catch[0]
pos = [300, 128]
speed = random.randint(5, 10)
count = 0
global birds
birds = True
gameOver = False

ratioList = []
blinkCounter = 0
counter = 0
List = []
finalList = []
def_counter = 0
selectionSpeed = 8
btn_size = 40

timeStart = time.time()  # 시작 시간은 웹캠이 열리는 시점의 현재시간

def text_def(xy, text_name, fontstyle, text_color):
    global image
    image = Image.fromarray(image)
    draw = ImageDraw.Draw(image)
    draw.text(xy=xy, text=text_name, font=fontstyle, fill=text_color)
    image = np.array(image)


def resetObject():
    global birds
    pos[0] = random.randint(0, 1180)
    pos[1] = 0
    randNo = random.randint(0, 1000000)  # change the ratio of eatables/ non-eatables
    currentObject = catch[random.randint(0, 3)]
    birds = True
    return currentObject

def gen(cap):
    global image, eye_dist, blinkCounter, timeStart, totalTime, gameOver, currentObject, eye_dist, counter, count,birds
    with mp_hands.Hands(max_num_hands=2, min_detection_confidence=0.5, min_tracking_confidence=0.5) as hands:
        while True:
            success, image = cap.read()
            image = cv2.flip(image, 1)
            results = hands.process(image)
            et.overlay(image, *(50, 50), 40, 40, logo)
            if time.time() - timeStart < totalTime:
                if gameOver is False:
                    text_def((100, 35), '눈을 깜빡하면서 새를 잡아보세요.', font, (255, 255, 255))
                    image, faces = detector.findFaceMesh(image, draw=False)
                    image = cvzone.overlayPNG(image, currentObject, pos)
                    pos[1] += speed

                    if pos[1] > 520:
                        currentObject = resetObject()

                    if faces:
                        face = faces[0]
                        up = face[159]  # Lefteye
                        down = face[23]
                        left = face[130]
                        right = face[243]

                        upDown, _ = detector.findDistance(up, down)
                        leftRight, _ = detector.findDistance(left, right)

                        cx, cy = (up[0] + down[0]) // 2, (up[1] + down[1]) // 2
                        dist, _ = detector.findDistance((cx, cy), (pos[0] + 50, pos[1] + 50))

                        ratio = int((upDown / leftRight) * 100)
                        ratioList.append(ratio)
                        if len(ratioList) > 3:
                            ratioList.pop(0)
                        ratioAvg = sum(ratioList) / len(ratioList)
                        if ratioAvg < eye_dist and counter == 0:
                            eyeStatus = "Open"
                            blinkCounter += 1
                            color = (0, 200, 0)
                            counter = 1
                        if counter != 0:
                            eyeStatus = "Closed"
                            counter += 1
                            if counter > 10:
                                counter = 0
                                color = (255, 0, 255)
                                if birds:
                                    currentObject = resetObject()
                                    count += 1
                                    List.append({
                                        'ID': userID,
                                        '시간': nowDatetime,
                                        '점수': str(count)
                                    })
                                else:
                                    gameOver = True
                            cv2.putText(image, eyeStatus, (1050, 680), cv2.FONT_HERSHEY_COMPLEX, 2, (255, 0, 255), 2)
                        cvzone.putTextRect(image, f'Score:  {str(count)}', (50, 680), scale=2, colorR=(255, 0, 255))
                cv2.putText(image, f'Time: {int(totalTime - (time.time() - timeStart))}', (1000, 80), 1, 3,
                            (255, 0, 255), 3)
            else:
                h, w, _ = background.shape
                image[int(360 - h / 2):int(360 + h / 2), int(630 - w / 2):int(630 + w / 2)] = background

                cv2.putText(image, "Game Over", (320, 300), cv2.FONT_HERSHEY_PLAIN, 7, (255, 0, 255), 10)
                cv2.putText(image, f'Your Score: {str(count)}', (450, 400), 1, 3, (255, 0, 255), 4)

                text_def((400, 470), " R = 재 시 작 ", font, (0, 0, 0))
                text_def((710, 470), " Q =  종 료 ", font, (50, 50, 255))

            cv2.imshow("Game", image)
            key = cv2.waitKey(1)
            if key == ord('r'):
                timeStart = time.time()
                resetObject()
                gameOver = False
                count = 0
                currentObject = catch[0]
                birds = True

            elif key == ord('q'):
                break

    final_List = List[-1]
    finalList.append(final_List)
    df = pd.DataFrame(finalList)
    df.to_csv('C:/Users/user/Desktop/pythonProject/pythonProject/Git/Flask/FlaskDB/AI/static/csv/게임.csv')
    print(finalList)
    print('저장 완료됬습니다.')
    cap.release()
    cv2.destroyAllWindows()

@bp.route('/game_camera')
def video_feed():
    global cap
    if Response(gen(cap),mimetype='multipart/x-mixed-replace; boundary=frame'):
        return render_template("test/game.html")    # 윈도우창이 출력시 카메라 페이지로 다시 돌아간다

Flask/FlaskDB/AI/views/main_views.py
from flask import Blueprint , render_template , request , jsonify
from ..models import User
from ..static.assets.module import hospital as hi, Search_NaverKin as NK, Search_NaverBlog as NB, ExtractByNum as EN

bp = Blueprint('main' , __name__ , url_prefix='/')

# 프로필 작업 해야함
@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/about')
def about():
    return render_template('about.html')

@bp.route('/contact')
def contact():
    return render_template('contact.html')

@bp.route('/pricing')
def pricing():
    return render_template('pricing.html')

@bp.route('/faq')
def faq():
    return render_template('faq.html')

# 챗봇
@bp.route('/chatbot1', methods=['GET','POST'])
def chatbot1():
    print('-'*50)
    req = request.get_json(force=True)
    print(req)
    ip_address = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
    responseID = req['responseId']
    result = req['queryResult']

    params = result['outputContexts'][0]['parameters']
    news_menu = params['news_menu']


    UserText = result['queryText']
    action = result['action']  # 1 : dialogflow에서 설정한 action 값
    print(ip_address, responseID, action, UserText)
    '''Dialogflow 내 action (웹훅 사용 리스트)
    NewsBot.NewsBot-custom.SelectSubMenu-custom  //뉴스봇 메뉴 선택 후 키원드 입력받은 follow intent
    '''
    if action == 'NewsBot.NewsBot-custom.NewsBot-custom-custom' and news_menu == "지식인":
        selected_num = 5 #보여줄 갯수 (default = 5)
        keyword = UserText
        df_NaverKin = NK.df_Search_NaverKin(keyword) #키워드 기반 네이버 지식인 api 20행 데이터프레임 추출
        df_ExtractByNum = EN.df_ExtractByNum(df_NaverKin, selected_num) # 20행의 데이터프레임 중 selected_num 만큼 랜덤 출력
        list_info = []
        for i in range(len(df_ExtractByNum)):
            title = df_ExtractByNum['Title'].iloc[i]
            link = df_ExtractByNum['Link'].iloc[i]
            description = df_ExtractByNum['Description'].iloc[i]
            arr_info = {
                "type": "info",
                "title": title,
                "subtitle": description,
                "actionLink": link
            }
            divider = {"type": "divider"}
            list_info.append(arr_info) # info 스타일
            list_info.append(divider) # 구분선
        r = jsonify(
            fulfillment_text = UserText + '결과는 다음과 같습니다.',
            fulfillment_messages=[{"payload": {"richContent": [list_info]}
                                   }
                                  ]
        )
        return r
    elif action == 'NewsBot.NewsBot-custom.NewsBot-custom-custom' and news_menu == "블로그":
        selected_num = 5  # 보여줄 갯수 (default = 5)
        keyword = UserText
        df_NaverBlog = NB.df_Search_NaverBlog(keyword)  # 키워드 기반 네이버 지식인 api 20행 데이터프레임 추출
        df_ExtractByNum = EN.df_ExtractByNum(df_NaverBlog, selected_num)  # 20행의 데이터프레임 중 selected_num 만큼 랜덤 출력
        list_info = []
        for i in range(len(df_ExtractByNum)):
            title = df_ExtractByNum['Title'].iloc[i]
            link = df_ExtractByNum['Link'].iloc[i]
            description = df_ExtractByNum['Description'].iloc[i]
            arr_info = {
                "type": "info",
                "title": title,
                "subtitle": description,
                "actionLink": link
            }
            divider = {"type": "divider"}
            list_info.append(arr_info)  # info 스타일
            list_info.append(divider)  # 구분선
        r = jsonify(
            fulfillment_text=UserText + '결과는 다음과 같습니다.',
            fulfillment_messages=[{"payload": {"richContent": [list_info]}
                                   }
                                  ]
        )
        return r


@bp.route('/navi', methods=['GET','POST'])
def navi():
    if request.method == "POST":
        if request.form['latlngbtn']:
            # 버튼에서 받아온 사용자 현위치 값 위도,경도로 분리
            latlng = eval(request.form['latlngbtn'])
            lat = float(latlng['lat'])
            lng = float(latlng['lng'])

            # 현위치와 가까운 안과,약국 각각 10곳 df 출력 함수 실행
            # 안과 테이블['hospital_info'],약국테이블['pharmacy_info']

            db2 = hi.ConnectDB()  # db 연결 함수 실행 = 메인 서버로 파라미터 따로 없음
            htop10_df = hi.Ophthalmology10(db2, 'hospital_info',lat,lng)  # 파라미터 : db, db테이블, 위도, 경도

            db2 = hi.ConnectDB()  # db 연결 함수 실행 = 메인 서버로 파라미터 따로 없음
            ptop10_df = hi.Ophthalmology10(db2, 'pharmacy_info', lat, lng)  # 파라미터 : db, db테이블, 위도, 경도

            # df를 2차원 딕셔너리로 저장
            htop10_df_dict = htop10_df.to_dict("records")  # body 부분 테이블용 병원 info
            ptop10_df_dict = ptop10_df.to_dict("records")  # body 부분 테이블용 약국 info

            # print(type(latlng), latlng)
            # print(type(htop10_df_dict), htop10_df_dict)
            # print(type(ptop10_df_dict), ptop10_df_dict)

            return render_template('navi_userlocation.html', info=htop10_df_dict, pinfo=ptop10_df_dict, latlng=latlng)

    return render_template('navi.html')
    ## else 로 하지 않은 것은 POST, GET 이외에 다른 method로 넘어왔을 때를 구분하기 위함

@bp.route('/navi/userlocation')
def userlocation():
    return render_template('navi_userlocation.html')

Flask/FlaskDB/AI/views/test_views.py
from flask import Blueprint , request , render_template , g , flash , url_for , redirect
from .. import db
from ..models import User , Test
from AI.forms import CataractForm
from AI.views.auth_views import login_required
from datetime import datetime
from werkzeug.utils import redirect
import matplotlib.pyplot as plt
plt.rc('font', family='NanumGothic') # For Windows
import warnings
warnings.filterwarnings('ignore')
from ..AI_model import cataract_predict as cp

bp = Blueprint('test' , __name__ , url_prefix='/test')

@bp.route('/cataract_main')
@login_required # @login_required 데코레이터
def cataract_main():
    return render_template('test/cataract_main.html')

# 백내장 테스트
@bp.route('/cataract_img', methods=['GET', 'POST'])
@login_required # @login_required 데코레이터
def Cataract_img():
    form = CataractForm()
    print('Start')
    if request.method == "POST":
        print('POST')
        file = request.files['image']
        if not file: return render_template('test/cataract_img.html', label="No Files")
        print('file uploaded successfully')

        class_name, score = cp.image_test(file)
        print(class_name)
        print(score)
        alert = f'{round(score)}%가 {class_name}입니다'
        print(alert)
        flash(alert)

        # if request.method == "GET" and form.validate_on_submit():
        #
        #     test = Test.query.filter_by(user=g.user, cataract=form.cataract.data, accuracy=form.accuracy.data,
        #                                 run_date=datetime.now())
        #
        #     db.session.add(test)
        #     db.session.commit()
        #     return redirect(url_for('test.Cataract'))
        return render_template("test/cataract_img.html", class_name=class_name, score=score , alert=alert , form=form)
    else:
        print('GET')
        return render_template("test/cataract_img.html")

Flask/FlaskDB/AI/templates/base.html
<!-- 상단 네비바랑 하단부분을 저장해두고 바디만을 비워두고 비슷한 페이지에 붙러서 사용하는 html 파일. -->

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.104.2">
        <title>Eye조아</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/css/styles.css" rel="stylesheet" />

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/js/scripts.js"></script>

    </head>


<body class="d-flex flex-column h-100">




<body class="flex-shrink-0">
   <!-- Navigation-->
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container-fluid">
           <a class="navbar-brand" href="{{ url_for('main.index') }}">Eye조아</a>
           <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
           <a class="navbar-brand" href="{{ url_for('main.index') }}">
<!--               <img src="/static/assets/img/free-icon-eye-1820057_negative.png" width="50" height="50">-->
           </a>
           <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                   <li class="nav-item"><a class="nav-link text-white" href="{{ url_for('main.index') }}">홈</a></li>
                   <li class="nav-item"><a class="nav-link text-white" href="{{ url_for('main.about') }}">소개</a></li>
                   <li class="nav-item dropdown">
                       <a class="nav-link dropdown-toggle text-white" id="navbarDropdownTest" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">검사</a>
                       <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownTest">
                           <li><a class="dropdown-item" href="{{ url_for('test.cataract_main') }}">백내장 검사</a></li>
                           <li><a class="dropdown-item" href="{{ url_for('glaucoma.glaucoma') }}">녹내장 검사</a></li>
                           <li><a class="dropdown-item" href="{{ url_for('eyetest.eyetest') }}">시력 검사</a></li>
                           <li><a class="dropdown-item" href="{{ url_for('astigmatism.astigmatism') }}">난시 검사</a></li>
                           <li><a class="dropdown-item" href="{{ url_for('macular.macular') }}">황반변성 검사</a></li>
                           <li><a class="dropdown-item" href="{{ url_for('color.color') }}">색각 검사</a></li>
                       </ul>
                   </li>
                   <li class="nav-item"><a class="nav-link text-white" href="{{ url_for('game.game') }}">게임</a></li>
                   <li class="nav-item"><a class="nav-link text-white" href="{{ url_for('main.navi') }}">의료/편의시설</a></li>
<!--                   <li class="nav-item"><a class="nav-link text-white" href="{{ url_for('main.faq') }}">고객센터</a></li>-->
                   <li class="nav-item"><a class="nav-link text-white" href="{{ url_for('question._list') }}">질문 게시판</a></li>
<!--                   <li class="nav-item dropdown">-->
<!--                       <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">질문 게시판</a>-->
<!--                       <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">-->
<!--                           <li><a class="dropdown-item" href="{{ url_for('question._list') }}">질문 게시판</a></li>-->
<!--                           <li><a class="dropdown-item" href="{{ url_for('question.create') }}">Blog Post</a></li>-->
<!--                       </ul>-->
<!--                   </li>-->
<!--                   <li class="nav-item dropdown">-->
<!--                       <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Portfolio</a>-->
<!--                       <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">-->
<!--                           <li><a class="dropdown-item" href="portfolio-overview.html">Portfolio Overview</a></li>-->
<!--                           <li><a class="dropdown-item" href="portfolio-item.html">Portfolio Item</a></li>-->
<!--                       </ul>-->
<!--                   </li>-->
               </ul>

               {% if g.user %}
               <a class="nav-link dropdown-toggle text-white" id="navbar" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ g.user.username }}
               <img class="img-fluid rounded mb-sm" src="/static/assets/img/login.png" alt="..." /></a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item profile-link" href="#">
                            <img class="img-fluid rounded mb-sm" src="/static/assets/img/user.png" alt="..." />
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                내 정보
                            </a>
                        <a class="dropdown-item profile-link" href="#">
                            <img class="img-fluid rounded mb-sm" src="/static/assets/img/profile.png" alt="..." />
                                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                계정설정
                            </a>

                        <a class="dropdown-item" href="{{ url_for('auth.logout') }}"><img class="img-fluid rounded mb-sm" src="/static/assets/img/logout.png" alt="..." />로그아웃</a>
                    </li>
                </ul>
                {% else %}
              <ul class="navbar-nav  mb-2 mb-lg-0">
                  <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.signin') }}">로그인</a></li>
                 <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a></li>
              </ul>
               {% endif %}
           </div>
       </div>
   </nav>
</body>







<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
{% block script %}

<!-- 자바스크립트 Start -->
<script type='text/javascript'>

<!-- 삭제 팝업 스크립트-->
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

<!-- 추천 스크립트 -->
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

</script>
{% endblock %}
<!-- 자바스크립트 End -->
</body>

<!--            &lt;!&ndash; Footer&ndash;&gt;-->
<!--        <footer class="bg-dark py-4 mt-auto">-->
<!--            <div class="container px-5">-->
<!--                <div class="row align-items-center justify-content-between flex-column flex-sm-row">-->
<!--                    <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Your Website 2022</div></div>-->
<!--                    <div class="col-auto">-->
<!--                        <a class="link-light small" href="#!">Privacy</a>-->
<!--                        <span class="text-white mx-1">&middot;</span>-->
<!--                        <a class="link-light small" href="#!">Terms</a>-->
<!--                        <span class="text-white mx-1">&middot;</span>-->
<!--                        <a class="link-light small" href="#!">Contact</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </footer>-->

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="/static/js/scripts.js"></script>

<script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
<meta name="viewport" content="width-device-width, initial-scale=1">
<df-messenger
  chat-title="Test_Main"
  agent-id="91bf2708-eeda-4f14-a0e0-858342f60a10"
  language-code="ko"
></df-messenger>
<style>

  df-messenger {
   --df-messenger-bot-message: #EDFDE7;
   --df-messenger-button-titlebar-color: #B4C3FF;
   --df-messenger-chat-background-color: #EBFBFF;
   --df-messenger-font-color: #000000;
   --df-messenger-send-icon: #878fac;
   --df-messenger-user-message: #479b3d;
    }
</style>


</html>

Flask/FlaskDB/AI/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

Flask/FlaskDB/AI/templates/index2.html
{% extends 'base.html' %}
{% block content %}

    <body>

        <!-- Page Content-->
        <section><img class="img-fluid" id="banner" src="static/assets/img/test_img.jpg" alt="..." />
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-6">
                        <h1 class="mt-5">The Big Picture</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt voluptates rerum eveniet sapiente repellat esse, doloremque quod recusandae deleniti nostrum assumenda vel beatae sed aut modi nesciunt porro quisquam voluptatem.</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="static/js/scripts.js"></script>
    </body>

{% endblock %}